#include "core/io/stream_peer.h"

class StreamPeerBitBuffer: public StreamPeerBuffer {
    GDCLASS(StreamPeerBitBuffer, StreamPeerBuffer);
    public:
        uint32_t bool_position = 0;
        uint32_t num_allocated_bools = 0;
        uint32_t bool_bytes = 0;
        
        virtual String _to_string() override;
        void reset();
        void bit_buffer_clear();
        void init(uint32_t with_size, uint32_t allocated_bools);
        static Ref<StreamPeerBitBuffer> allocate(uint32_t with_size, uint32_t allocated_bools);
        PackedByteArray export_data(bool until_position);
        void import(PackedByteArray bytes);
        PackedByteArray get_bools(bool until_position);
        static Ref<StreamPeerBitBuffer> decode(PackedByteArray bytes);
        PackedByteArray get_non_bools(bool until_position);
        // Array get_bools_as_array();
        void ensure_bools_allocated();
        void reallocate_bools(uint32_t amount);
        void put_bool(bool value);
        bool put_eval(bool evaluation);
        bool get_bool();
        void seek_var_pos(int position);
        int get_var_pos();
        void jump(int amount);
        void put_v2(Vector2 v2);
        Vector2 get_v2();
        void put_v3(Vector3 v3);
        Vector3 get_v3();
        void put_v4(Vector4 v4);
        Vector4 get_v4();
        void put_v2i(Vector2i v2);
        Vector2i get_v2i();
        void put_v3i(Vector3i v3);
        Vector3i get_v3i();
        void put_v4i(Vector4i v4);
        Vector4i get_v4i();
        void put_r2(Rect2 r2);
        Rect2 get_r2();
        void put_r2i(Rect2i r2i);
        Rect2i get_r2i();
        void put_quat(Quaternion quat);
        Quaternion get_quat();
        void put_color(Color color);
        Color get_color();
        void put_udynamic(uint64_t num);
        int get_udynamic();
        void put_dynamic(int64_t num);
        int get_dynamic();
        void put_n8(float num, float unit);
        float get_n8(float unit);
        void put_n16(float num, float unit);
        float get_n16(float unit);
        void put_n32(float num, float unit);
        float get_n32(float unit);
        void put_n64(float num, float unit);
        float get_n64(float unit);
        void put_r8(float num, float unit);
        float get_r8(float unit);
        void put_r16(float num, float unit);
        float get_r16(float unit);
        void put_r32(float num, float unit);
        float get_r32(float unit);
        void put_r64(float num, float unit);
        float get_r64(float unit);
        void put_rotation(Vector3 rot);
        Vector3 get_rotation();
        void put_rotation_half(Vector3 rot);
        Vector3 get_rotation_half();
        void put_nv2(Vector2 v2, float unit);
        Vector2 get_nv2(float unit);
        void put_rv2_half(Vector2 v2, float unit);
        Vector2 get_rv2_half(float unit);
        void put_nv2_half(Vector2 v2, float unit);
        Vector2 get_nv2_half(float unit);
        void put_probabalistic_enum(uint64_t value);
        uint64_t get_probabalistic_enum(uint64_t enum_max);
        uint32_t get_bool_position();
        void set_bool_position(uint32_t p_bool_position);
        uint32_t get_num_allocated_bools();
        void set_num_allocated_bools(int p_num_allocated_bools);
        uint32_t get_bool_bytes();
        void set_bool_bytes(int p_bool_bytes);
        static void _bind_methods();
};
